web:
  upload-path: G:/images

spring:
  resources:
    static-locations: file:${web.upload-path}
  redis:
    host: 82.157.54.117
    port: 6379
    database:
      db0: 0
      db1: 1
    timeout: 3000
    pool:
      max-active: 100
      max-idle: 3
      min-idle: 0
      max-wait: -1
    password: 123
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.157.54.117:3306/policy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: policy
    password: 2023Bjtu
#    url: jdbc:mysql://127.0.0.1:3306/search_engine_v2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
#    username: root
#    password: 123

  #RabbitMQ
  rabbitmq:
    #服务器
    host: 82.157.54.117
    #用户名
    username: guest
    #密码
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 20
        #限制消费者每次只能处理一条消息，处理完在继续下一条消息
        prefetch: 1
        #启动是默认启动容器
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #最大重试间隔时间
        max-interval: 10000ms
        #重试的间隔乘数，比如配2。0  第一等10s 第二次等20s 第三次等40s
        multiplier: 1



server:
  port: 8081






mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.searchengine.entity

